name: 📡 Generate OpenAlex RSS

on:
  workflow_dispatch:  # Allows manual run (no schedule yet)
  # Once working, add:
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests feedgen

      - name: Generate and Commit RSS
  env:
    CONTACT_EMAIL: "you@gmail.com"
  run: |
    # Create RSS content
    cat > rss-test.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>✅ SUCCESS</title>
    <link>https://openalex.org</link>
    <description>Your OpenAlex RSS pipeline is working!</description>
  </channel>
</rss>
EOF

    # Create rss/ and move file
    mkdir -p rss
    mv rss-test.xml rss/test.xml

    # Commit
    git config user.name "GitHub Action"
    git config user.email "action@github.com"
    git add rss/test.xml
    git commit -m "🤖 First RSS" || echo "Skip commit"
    git push
